### PR TITLE
Use xyz::guard in indirect and polymorphic

### PR DESCRIPTION
**Pull request by jbcoe**
@Twon Do we want this or does it raise cognitive load for readers of what is mean to be a reference implementation?

### CODE REVIEW

**Review by Twon — APPROVED** [review]

**Comment by Twon** [comment]
> @Twon Do we want this or does it raise cognitive load for readers of what is mean to be a reference implementation?

Looks sensible from an exception safety point of view!

**Comment by jbcoe** [comment]
I'll press on then. Will finish this tonight. Code was exception-safe before.

**Comment by Twon** [comment]
> Code was exception-safe before.

Of course it was... lack of sleep due to jet lag is getting to me :(

**Comment by jbcoe** [comment]
Using guard in C++14 implementation looks a bit trickier, some issues with RVO. Will defer for now.

**Pull request closed without merging**
