### PR TITLE
Add initial benchmark code

### LINKED ISSUE #60: Add benchmarks
Use https://github.com/google/benchmark to compare indirect and polymorphic with traditional component-based designs.

### PR DESCRIPTION
**Pull request by jbcoe**
Add https://github.com/google/benchmark

Need to add CMake support and more benchmarks

fixes #60

### CODE REVIEW

**Comment by jbcoe** [comment]
Benchmark results on GCC-13 from an Azure Ubuntu 22 box:

```
Run on (2 X 2593.91 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x1)
  L1 Instruction 32 KiB (x1)
  L2 Unified 1024 KiB (x1)
  L3 Unified 36608 KiB (x1)
Load Average: 0.00, 0.14, 0.23
------------------------------------------------------------------------
Benchmark                              Time             CPU   Iterations
------------------------------------------------------------------------
RawPtrClone                         36.6 ns         36.5 ns     19059579
UniquePtrClone                      17.9 ns         17.9 ns     39066206
PolymorphicCopy                     19.8 ns         19.8 ns     35268926
RawPointerVectorCopy            60393413 ns     60386308 ns           12
UniquePointerVectorCopy         60642893 ns     60635691 ns           11
PolymorphicVectorCopy           72293546 ns     72282300 ns            9
RawPointerArrayCopy                25286 ns        25284 ns        27557
UniquePointerArrayCopy             25586 ns        25583 ns        27366
PolymorphicArrayCopy               26919 ns        26917 ns        26003
RawPointerVectorAccumulate       3809286 ns      3808843 ns          182
UniquePointerVectorAccumulate    3818907 ns      3818544 ns          172
PolymorphicVectorAccumulate      5507102 ns      5485146 ns          126
```

**Comment by jbcoe** [comment]
Benchmark results from AppleClang on an M2 Max

```
Run on (12 X 24.1207 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB (x12)
  L1 Instruction 128 KiB (x12)
  L2 Unified 4096 KiB (x3)
Load Average: 2.34, 1.62, 1.43
------------------------------------------------------------------------
Benchmark                              Time             CPU   Iterations
------------------------------------------------------------------------
RawPtrClone                         8.85 ns         8.85 ns     75612733
UniquePtrClone                      13.0 ns         13.0 ns     53030705
PolymorphicCopy                     16.9 ns         16.9 ns     40696255
RawPointerVectorCopy            15894837 ns     15894864 ns           44
UniquePointerVectorCopy         16016035 ns     16015651 ns           43
PolymorphicVectorCopy           29882009 ns     29876391 ns           23
RawPointerArrayCopy                13080 ns        13079 ns        52504
UniquePointerArrayCopy             13240 ns        13240 ns        51741
PolymorphicArrayCopy               25941 ns        25938 ns        27170
RawPointerVectorAccumulate       1677905 ns      1677692 ns          419
UniquePointerVectorAccumulate    1665680 ns      1665680 ns          419
PolymorphicVectorAccumulate      1689198 ns      1689070 ns          412
```

**Comment by jbcoe** [comment]
Results from an M2 Max Macbook Pro

```
bazel run -c opt :benchmark
```

```
Run on (12 X 24.1207 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB (x12)
  L1 Instruction 128 KiB (x12)
  L2 Unified 4096 KiB (x3)
Load Average: 2.05, 1.68, 1.84
---------------------------------------------------------------------------------------
Benchmark                                             Time             CPU   Iterations
---------------------------------------------------------------------------------------
Indirect_BM_RawPtrClone                            8.31 ns         8.28 ns     75677312
Indirect_BM_UniquePtrClone                         12.0 ns         12.0 ns     58259053
Indirect_BM_IndirectCopy                           12.0 ns         12.0 ns     58046487
Indirect_BM_RawPointerVectorCopy               15002846 ns     15002848 ns           46
Indirect_BM_UniquePointerVectorCopy            15022493 ns     15022478 ns           46
Indirect_BM_IndirectVectorCopy                 15006601 ns     15006609 ns           46
Indirect_BM_RawPointerArrayCopy                   12385 ns        12385 ns        55857
Indirect_BM_UniquePointerArrayCopy                12311 ns        12311 ns        56119
Indirect_BM_IndirectArrayCopy                     12429 ns        12429 ns        55678
Indirect_BM_RawPointerVectorAccumulate           365149 ns       365147 ns         1882
Indirect_BM_UniquePointerVectorAccumulate        373228 ns       373228 ns         1799
Indirect_BM_IndirectVectorAccumulate             383832 ns       383832 ns         1909
Polymorphic_BM_RawPtrClone                         11.7 ns         11.7 ns     69398317
Polymorphic_BM_UniquePtrClone                      12.8 ns         12.8 ns     53436338
Polymorphic_BM_PolymorphicCopy                     15.6 ns         15.6 ns     45819915
Polymorphic_BM_RawPointerVectorCopy            16167531 ns     16167405 ns           42
Polymorphic_BM_UniquePointerVectorCopy         16167453 ns     16167395 ns           43
Polymorphic_BM_PolymorphicVectorCopy           31551327 ns     31501762 ns           21
Polymorphic_BM_RawPointerArrayCopy                13369 ns        13369 ns        51451
Polymorphic_BM_UniquePointerArrayCopy             13545 ns        13545 ns        51768
Polymorphic_BM_PolymorphicArrayCopy               26309 ns        26289 ns        26930
Polymorphic_BM_RawPointerVectorAccumulate       1651239 ns      1651239 ns          422
Polymorphic_BM_UniquePointerVectorAccumulate    1653512 ns      1653512 ns          422
Polymorphic_BM_PolymorphicVectorAccumulate      1702068 ns      1702046 ns          409
```

**Comment by StuartAbercrombie** [comment]
M1 Pro Apple clang version 14.0.3
```
Run on (10 X 24.1209 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB (x10)
  L1 Instruction 128 KiB (x10)
  L2 Unified 4096 KiB (x5)
Load Average: 4.21, 4.52, 6.95
---------------------------------------------------------------------------------------
Benchmark                                             Time             CPU   Iterations
---------------------------------------------------------------------------------------
Indirect_BM_RawPtrClone                            9.76 ns         9.76 ns     71889988
Indirect_BM_UniquePtrClone                         15.6 ns         15.6 ns     45348536
Indirect_BM_IndirectCopy                           15.4 ns         15.4 ns     45333851
Indirect_BM_RawPointerVectorCopy               19391425 ns     19371750 ns           36
Indirect_BM_UniquePointerVectorCopy            19461076 ns     19420800 ns           35
Indirect_BM_IndirectVectorCopy                 19465641 ns     19436806 ns           36
Indirect_BM_RawPointerArrayCopy                   15086 ns        15071 ns        46237
Indirect_BM_UniquePointerArrayCopy                15331 ns        15320 ns        45573
Indirect_BM_IndirectArrayCopy                     15616 ns        15595 ns        45541
Indirect_BM_RawPointerVectorAccumulate           411921 ns       411739 ns         1647
Indirect_BM_UniquePointerVectorAccumulate        418618 ns       418617 ns         1721
Indirect_BM_IndirectVectorAccumulate             412682 ns       412519 ns         1687
Polymorphic_BM_RawPtrClone                         13.5 ns         13.5 ns     59916630
Polymorphic_BM_UniquePtrClone                      16.3 ns         16.2 ns     42843590
Polymorphic_BM_PolymorphicCopy                     18.9 ns         18.9 ns     37574612
Polymorphic_BM_RawPointerVectorCopy            20482603 ns     20451235 ns           34
Polymorphic_BM_UniquePointerVectorCopy         20761054 ns     20706294 ns           34
Polymorphic_BM_PolymorphicVectorCopy           29148900 ns     28728960 ns           25
Polymorphic_BM_RawPointerArrayCopy                15610 ns        15598 ns        44711
Polymorphic_BM_UniquePointerArrayCopy             15848 ns        15846 ns        43927
Polymorphic_BM_PolymorphicArrayCopy               20542 ns        20514 ns        34279
Polymorphic_BM_RawPointerVectorAccumulate       1808298 ns      1808018 ns          380
Polymorphic_BM_UniquePointerVectorAccumulate    1796649 ns      1796645 ns          389
Polymorphic_BM_PolymorphicVectorAccumulate      1803794 ns      1803768 ns          383
```

**Review by Twon — APPROVED** [review]
Look great, sterling effort!

**Pull request merged**
