### PR TITLE
Try to raise code coverage

### LINKED ISSUE #49: Raise code coverage by using type with throwing copy constructor

### PR DESCRIPTION
**Pull request by jbcoe**
fixes #49

### CODE REVIEW

**Comment by jbcoe** [comment]
Coverage of headers is back to 100%.

**Comment by jbcoe** [comment]
This PR is a bit too involved for me to just merge.

**Comment by Twon** [comment]
Just pushed up a change in the way the exception works to avoid missing coverage of the `what()` method.  As a result no coverage failures.

**Review by Twon — APPROVED** [review]
Looks great, thanks for adding this!

**Pull request merged**
