### PR TITLE
Add compile_checks to CMakeLists.txt

### PR DESCRIPTION
**Pull request by jbcoe**
Exclude compile checks from MSVC as there are issues with constexpr/consteval

### CODE REVIEW

**Review by Twon — DISMISSED** [review]
Nice, it will be good to support these via CMake

**Comment by jbcoe** [comment]
@Twon weird Visual Studio build errors that I can't decipher - can you repro locally?

**Comment by Twon** [comment]
> @Twon weird Visual Studio build errors that I can't decipher - can you repro locally?

Looking into it, can reproduce locally

**Comment by jbcoe** [comment]
> > @Twon weird Visual Studio build errors that I can't decipher - can you repro locally?
> 
> Looking into it, can reproduce locally

There have been bugs: https://developercommunity.visualstudio.com/t/problem-with-consteval-function/1224555

**Comment by Twon** [comment]
> > @Twon weird Visual Studio build errors that I can't decipher - can you repro locally?
> 
> Looking into it, can reproduce locally

Looks like a compiler bug... I've cut this down to a minimal example and it still fails with no error message.  Will try to create an example on Godbolt

**Comment by Twon** [comment]
> > > @Twon weird Visual Studio build errors that I can't decipher - can you repro locally?
> > 
> > 
> > Looking into it, can reproduce locally
> 
> Looks like a compiler bug... I've cut this down to a minimal example and it still fails with no error message. Will try to create an example on Godbolt

Reproduction case on Godbolt: https://godbolt.org/z/Ko3EMoo1K

**Comment by jbcoe** [comment]
@Twon Can we exclude these from MSVC for now? My CMake-fu is weak

**Review by Twon — APPROVED** [review]

**Pull request merged**
